### ISSUE TITLE
Detects indents in json-mode incorrectly

### ISSUE THREAD

**Issue by aaronjensen** [jscheid/dtrt-indent#29] opened 2017-03-24 15:22 UTC
I often get 4 space indent instead of 2 within json files. Here's an example:

```
{
  "extends": ["tslint:latest", "tslint-react"],
  "rules": {
    "array-type": [true, "array"],
    "arrow-parens": [true, "ban-single-arg-parens"],
    "arrow-return-shorthand": [true, "multiline"],
    "await-promise": true,
    "curly": false,
    "interface-name": [true, "never-prefix"],
    "match-default-export-name": true,
    "max-line-length": [true, 120],
    "member-access": false,
    "no-consecutive-blank-lines": [true, 1],
    "no-duplicate-super": true,
    "no-floating-promises": true,
    "no-trailing-whitespace": [true, "ignore-comments"],
    "no-unsafe-finally": true,
    "no-unused-expression": [true, "allow-fast-null-checks"],
    "object-literal-sort-keys": false,
    "ordered-imports": true,
    "prefer-const": true,
    "quotemark": [true, "single", "jsx-double"],
    "semicolon": [true, "never"],
    "trailing-comma": [true, {"multiline": "always", "singleline": "never"}],
    "variable-name": [true, "ban-keywords", "check-format", "allow-leading-underscore", "allow-pascal-case"],
    "jsx-alignment": true,
    "jsx-ban-props": true,
    "jsx-boolean-value": [true, "never"],
    "jsx-no-lambda": false,
    "jsx-no-string-ref": true,
    "jsx-self-close": true,
    "jsx-wrap-multiline": true,
    "jsx-no-multiline-js": false
  }
}
```

And `dtrt-indent-diagnosis`:

```
Guessing offset for /Users/aaronjensen/Source/epic-trello/tslint.json

Elapsed time for analysis: 0.001 seconds

Total relevant lines: 33 out of 36 (limit: 5000)

Histogram:

     3x   2 spaces
    30x   4 spaces

Analysis:

  offset 2 works for 100.00% of relevant lines, matching 2 distinct offsets - merged with offset 4 (9.09% deviation, limit 20.00%)
  offset 4 works for  90.91% of relevant lines, matching 1 distinct offsets - CONSIDERED
  offset 3 works for   0.00% of relevant lines, matching 0 distinct offsets - rejected: too few distinct matching offsets (1 required)
  offset 5 works for   0.00% of relevant lines, matching 0 distinct offsets - rejected: too few distinct matching offsets (1 required)
  offset 6 works for   0.00% of relevant lines, matching 0 distinct offsets - rejected: too few distinct matching offsets (1 required)
  offset 7 works for   0.00% of relevant lines, matching 0 distinct offsets - rejected: too few distinct matching offsets (1 required)
  offset 8 works for   0.00% of relevant lines, matching 0 distinct offsets - rejected: too few distinct matching offsets (1 required)

Summary:

  Best guess is offset 4 with 90.91% matching lines (80.00% required)
  Hard tab percentage: 0.00% (0 lines), -100.00% superior to soft tabs (threshold 300.00%)
  Soft tab percentage: 100.00% (33 lines), inf% superior to hard tabs (threshold 300.00%)

Conclusion:

  Guessed offset 4 with 91% confidence.
  Change indent-tab-setting: yes, to nil
```

**Comment by rrthomas** [comment] 2017-03-24 15:29
The logic is working as intended. You can set `dtrt-indent-max-merge-deviation` to, in this case, `9.00`. If you'd like to suggest an improvement to the logic, please do!

**Comment by aaronjensen** [comment] 2017-03-24 15:31
It doesn't take into account the indentation rules of a file? It seems like things after `  "rules": {` have 2 * indent-size.

**Comment by rrthomas** [comment] 2017-03-24 15:33
Sorry, I don't understand what you mean by "indentation rules". Maybe read the docstring of `dtrt-indent-max-merge-deviation`, if you haven't already?

**Comment by aaronjensen** [comment] 2017-03-24 15:44
I was (incorrectly, it seems) assuming that dtrt-indent took into account how files are meant to be indented rather than just counting whitespace and guessing.

In other words, it could look at a json file like:

```
{
  foo: {
    bar: 3
  }
}
```

and know, that because indentation typically happens after a line ends w/ `{`, that the indentation setting *must* be 2. I'm sure that that would be a rather tricky and probably hard thing to implement, so I totally get why it works the way it does.

I set `dtrt-indent-max-merge-deviation` to 9.0 and I'll see how it goes. I really only ever have problems w/ eslint/tslint json rule files because of their particular shape. Thanks much for the help.

**Comment by rrthomas** [comment] 2017-03-24 15:52
Yes, I'm dtrt-indent is dumb; on the other hand, it's already quite complicated, and trying to infer how files are "meant to be" indented is probably a mug's game. If you have files that have explicit information on how they're supposed to be indented, that's fine, don't use dtrt-indent on them, and enforce their indentation (as `fmt` or `go fmt` do). `dtrt-indent` is meant for use when this information isn't available.

Closing.

**Closed by rrthomas** 2017-03-24 15:52 UTC
